### ISSUE TITLE
How much you could break it?

### ISSUE THREAD

**Issue by CaptainDumb** [YoshiCrafter29/YoshiCrafterEngine#70]
https://youtu.be/eMwE59LVfDg - see problems here

**Comment by YoshiCrafter29** [comment]
This is a problem with your computer.
The main issue here is an audio related issue.
It is caused whenever the game loses connection with the audio device.

You should probably check your audio drivers, and HaxeFlixel (the game engine used for fnf), since Yoshi Engine relies on these.

Not an engine problem, closing this issue.
